AWSTemplateFormatVersion: "2010-09-09"
Description: Simple Deployment pointing to existing S3 Bucket

Parameters:
  S3StackName:
    Type: String
    Default: my-s3-stack
    Description: Name of the S3 CloudFormation stack

Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: my-simple-function
      Runtime: python3.12
      Handler: index.handler
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/LambdaExecutionRole
      Code:
        S3Bucket: !ImportValue
          Fn::Sub: "${S3StackName}-BucketName"
        S3Key: deployment.zip
