AWSTemplateFormatVersion: '2010-09-09'
Description: Simple IAM Role Example

Resources:
  MyIamUser:
    Type: AWS::IAM:User
    Properties:
      UserName: !Ref MyIamUsername
      LoginProfile:
        Password: !Ref MyIamUserPassword
        PasswordResetRequired: false

Parameters:
  MyIamUsername:
    Type: String

  MyIamUserPassword:
    Type: String
    NoEcho: true
